### ISSUE TITLE
allow for untrusted certificate

### ISSUE THREAD

**Issue by rabbah** [psuter/wab#1]
using wab with a local deployment will generate a self-signed certificate error.
it would be nice to suppress this error (as it comes up at startup).

![screen shot 2016-11-30 at 11 02 04 am](https://cloud.githubusercontent.com/assets/4959922/20759944/7bc3ba52-b6ec-11e6-9de5-e14337a67ae6.png)

**Comment by psuter** [comment]
Did #4 address that to your satisfaction?

**Comment by rabbah** [comment]
It did in that it's pretty convenient to do from the CLI without changing the source for wab.
I think it's ok to defer an actual solution to the main repo where the properties should store if the host is trusted or not.
